---
title: "pipeline"
output: html_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(magrittr)
```

0. NetworKIN is installed
```{r}
source('R/install_networkin.R')
networkin_setup()
```

1. Generate NetworKIN input from phosphoproteomic data
```{r}
# Human phosphoproteomic data
source('R/networkin_input.R')
networkin_input(
  phospho_file = "data/imported/phospho_human_LAM.xlsx",
  phosphosites_column = "PhosphoSite",
  log2_column = "LAM-Log2(Relapse/diagnostic",
  fdr_column = "pvalue LAM",
  experiment = "human",
  species = 'hsa'
)

# Mouse phosphoproteomic data
source('R/networkin_input.R')
networkin_input(
  phospho_file = "data/imported/phospho_mouse.xlsx",
  phosphosites_column = "ProteinID-Phospho:Site",
  log2_column = "Log2",
  fdr_column = "Adj. p-value",
  experiment = "mouse",
  species = 'mmu'
)
```

2. Run NetworKIN
__may not work on Windows__
```{r}
source('R/run_networkin.R')
run_networkin(
  input_file = "data/outputs/networKIN_input_human.res",
  blastall_location <- "~/blast-2.2.17/bin/blastall",
  experiment = "human"
)
```

3. NetworKIN predictions filtering
Predictions that have a score in the top 20% of all predictions are kept. Predictions are kept for all sites (significantly deregulated or not deregulated).
```{r}
source('R/filter_predictions.R')
filter_predictions(
  predictions_file = 'data/outputs/networKIN_output_human.tsv',
  experiment = 'human'
)
```

4. NetworKIN Fisher exact test
```{r}
source('R/select_top_predictions.R')
select_top_predictions(predictions_file = 'data/analyses/filtered_networkin_predictions_human.csv',
                phospho_cleaned_file = 'data/outputs/phospho_clean_human.csv',
                experiment = 'human')
```


