# 3 Predictions filtering
Import NetworKIN predictions
```{r}
predictions <- read_tsv("data/outputs/networKIN_output.tsv", col_types = cols()) %>% 
  select(-`Target Name`, 
         # - `Kinase/Phosphatase/Phospho-binding domain`,
         -`Kinase/Phosphatase/Phospho-binding domain description`,
         -`Kinase/Phosphatase/Phospho-binding domain Name`) %>% 
  select("target_id" = `#Name`, 
         "protein_name" = `Target description`, 
         "phosphosite" = Position, 
         "kinase_phosphatase_phospho-binding" = `Kinase/Phosphatase/Phospho-binding domain`,
         "networkin_score" = `NetworKIN score`, 
         "netphorest_probability" = `NetPhorest probability`, 
         "family_tree" = Tree, 
         "netphorest_group" = `NetPhorest Group`)

```


```{r}
predictions %<>% 
  mutate(protein_phosphosite = str_c(target_id, phosphosite, sep = ":"))
```

# Filtering on significantly deregulated phosphosites
```{r}
FDR_threshold <- 0.05
FC_threshold <- 1.2
log2FC_threshold <- log2(FC_threshold)
humanized_proteo <- read_csv("data/outputs/humanized_phospho_results.csv", col_types = cols()) %>% 
  filter(`Adj. p-value` < FDR_threshold) %>% 
  filter(Log2 > log2FC_threshold | Log2 < -log2FC_threshold) %>% 
  mutate(MOD_RSD_human = str_extract(MOD_RSD_human, pattern = "^[:alnum:]+"),
         protein_phosphosite = str_c(ACC_ID_human, MOD_RSD_human, sep = ":"))

write_csv(humanized_proteo, "data/analyses/filtered_humanized_phospho_results.csv")

signif_predictions <-   #predictions only for significantly deregulated phosphosites
  predictions %>% 
    filter(protein_phosphosite %in% humanized_proteo$protein_phosphosite)
```


# Filtering on threshold
## Finding networkin threshold value
```{r}
threshold_fraction <- 0.8 #only the top 20% predictions will be kept for analysis

cumulated_scores <- signif_predictions %>% 
  count(networkin_score) 

cumulated_scores %<>% 
  bind_cols(., "cumulated_count" = cumsum(cumulated_scores$n))

total_score <- cumulated_scores$cumulated_count[nrow(cumulated_scores)]

cumulated_scores %<>% 
  mutate(count_fraction = cumulated_count/total_score)

networkin_score_threshold <- as.numeric(cumulated_scores %>% 
                                filter(count_fraction > threshold_fraction) %>% 
                                select(networkin_score) %>% 
                                slice(1))

rm(threshold_fraction, cumulated_scores, total_score)
```

## Applying filtering with this threshold
```{r}
signif_predictions %<>% 
  filter(networkin_score >= networkin_score_threshold)
```


# Export filtered predictions
```{r}
write_csv(signif_predictions, "data/analyses/filtered_predictions.csv")

rm(humanized_proteo, predictions, signif_predictions, networkin_score_threshold, FC_threshold, log2FC_threshold, FDR_threshold)
```


