#' In vitro database for IV-KEA
#' 
#' This database is used to perform IV-KEA. It indicates all phosphosites
#' phosphorylated by a set of 350 kinases according to an in vitro experiment.
#' @docType data
#' @usage data("invitrodb")
#' @format An object of class \code{"data.frame"}
#' @references This database was generated by Sugiyama et al., 2019
#' @keywords dataset
#' @examples 
#' data("invitrodb") 
#' head(invitrodb)
"invitrodb"
